export enum TypeDemande {
    PRET_AVANCE = 'PRET_AVANCE',
    CHANGEMENT_DE_SITUATION = 'CHANGEMENT_DE_SITUATION',
    AUTORISATION = 'AUTORISATION',
    CONGE = 'CONGE',
    DOCUMENT_ADMINISTRATIF = 'DOCUMENT_ADMINISTRATIF',
    MUTATION = 'MUTATION',
}
