version: '3.8'

services:
  spring-app:
    container_name: spring-app
    image: spring-app
    restart: always
    build: /var/lib/jenkins/workspace/devops
    ports:
      - "8089:8089"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - /var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: springdb
      MYSQL_ROOT_PASSWORD: root

  angular-app:
    build: /var/lib/jenkins/workspace/angular
    ports:
      - "4200:80"
    depends_on:
      - spring-app